# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Dantangfan"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
# markdown:           rdiscount

paginate: 10
paginate_path: "page/:num"

# 摘要
excerpt_separator:  '<!-- more -->'

# Navigation
nav:
  - name:           "HOME"
    href:           "//dantangfan.com"
  - name:           "Github"
    href:           "//github.com/dantangfan"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
